os:
#  - linux
  - osx

language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      - xvfb

install:
  - npm ci

script:
  - npm run citest
  - npm run package -- --version $TRAVIS_COMMIT --tag $TRAVIS_TAG

after_success:
  - ls -la dist
  - cat dist/Raw-Viewer*.zip | curl -F "file=@-" https://file.io/
