version: '{branch} #{build}'

environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm ci

test_script:
  - set FORCE_COLOR=1
  - npm test

build_script:
  - npm run package

after_build:
  - dir dist

build: off
