version: '{branch} #{build}'

environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm ci

test_script:
  - set FORCE_COLOR=1
  - npm test

after_test:
  - npm run package -- --version %APPVEYOR_REPO_COMMIT% --tag %APPVEYOR_REPO_TAG_NAME%
  - dir dist

build: off

artifacts:
  - path: 'dist\*.zip'

deploy:
  - provider: GitHub
    description: v$(APPVEYOR_REPO_TAG_NAME)
    artifact: 'dist\*.zip'
    auth_token:
      secure: 6iMMlHXl8pokHM9lubau52XP61dDapoR0TEQ5/4YmrxSAQAEifpEyrBF8TVRnHdv
    on:
      APPVEYOR_REPO_TAG: true
