version: '{branch} #{build}'

environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm ci

test_script:
  - set FORCE_COLOR=1
  - npm test

after_test:
  - echo Building Windows package
  - set
  - npm run package -- --version %APPVEYOR_REPO_COMMIT% --tag %APPVEYOR_REPO_TAG_NAME%
  - dir dist

build: off

artifacts:
  - path: 'dist\*.zip'
