version: '{branch} #{build}'

environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm ci

test_script:
  - set FORCE_COLOR=1
  - npm test

after_test:
  - npm run package -- --version %APPVEYOR_REPO_COMMIT% --tag %APPVEYOR_REPO_TAG_NAME%
  - dir dist

build: off

artifacts:
  - path: 'dist\*.zip'

deploy:
  - provider: GitHub
    description: v$(APPVEYOR_REPO_TAG)
    artifact: 'dist\*.zip'
    auth_token:
      secure: Ct7g0j7OphnlESFO+SgChc+GkeJz6oVdfg7fFO8RESqyGz8aDnldIMz26+X6rsmk
    on:
      APPVEYOR_REPO_TAG: true
