name: Node CI

on: [push]
env:
  CI: true
  FORCE_COLOR: 1
  NODE: 12.x  
jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: use node
        uses: actions/setup-node@v1
      - name: test
        run: |
          echo tests will go here
          which docker
          exit 1
  macos:
    runs-on: macOS-10.14
    env:
      CI: true
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v1
      - name: use node ${{ NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ NODE }}
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: |
          npm run package -- --version ${{ GITHUB_SHA }}
          ls dist
  windows:
    runs-on: windows-2019
    env:
      CI: true
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v1
      - name: use node ${{ NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ NODE }}
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: |
          npm run package -- --version ${{ GITHUB_SHA }}
          dir dist
          
