name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CI: true
  FORCE_COLOR: 1
  NODE: 12.x

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build --build-arg TRAVIS_COMMIT=${{ github.sha }} -t raw-viewer-build . -f- < .build-linux.dockerfile
          docker images
          docker run -d --rm --name rv raw-viewer-build  tail -f /dev/null
          docker cp rv:/dist dist
          docker kill rv
          ls -la dist
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: dist/*.{tar.gz,AppImage}
  macos:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}
      - name: info
        run: |
          node -v
          npm -v
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: |
          npm run package -- --version ${{ github.sha }}
          ls -la dist
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifacts
          path: dist/*.{zip,dmg}
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}
      - name: info
        run: |
          node -v
          npm -v
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: |
          npm run package -- --version ${{ github.sha }}
          dir dist
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: dist/*.{zip,exe}
